# Generated by Django 5.0.3 on 2024-04-04 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmplloyeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='name ', regex='^(?=.{3,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')])),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='gender ', regex='^(?=.{3,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')])),
                ('Phone_No', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')])),
                ('Address_Details', models.JSONField()),
                ('H_No', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='gender ', regex='^(?=.{3,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')])),
                ('Street', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='gender ', regex='^(?=.{3,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')])),
                ('City', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='gender ', regex='^(?=.{3,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')])),
                ('State', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='gender ', regex='^(?=.{3,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')])),
                ('Work_Experience', models.JSONField()),
                ('Company_Name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='gender ', regex='^(?=.{3,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')])),
                ('From_Date', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='gender ', regex='^(?=.{3,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')])),
                ('To_Date', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='gender ', regex='^(?=.{3,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')])),
                ('Address', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='gender ', regex='^(?=.{3,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')])),
                ('Qualifications', models.JSONField()),
                ('Qualification_Name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='gender ', regex='^(?=.{3,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')])),
                ('Percentage', models.FloatField()),
                ('Projects', models.JSONField()),
                ('Title', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='gender ', regex='^(?=.{3,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')])),
                ('Description', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='gender ', regex='^(?=.{3,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')])),
                ('Photo', models.TextField()),
            ],
            options={
                'db_table': 'Employee_Table',
            },
        ),
    ]
