# Generated by Django 5.0.3 on 2024-04-05 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplloyeemodel',
            name='Address',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='This field must contain only letters and numbers.', regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='emplloyeemodel',
            name='City',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='This field must contain only letters and numbers.', regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='emplloyeemodel',
            name='Company_Name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='This field must contain only letters and numbers.', regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='emplloyeemodel',
            name='Description',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='This field must contain only letters and numbers.', regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='emplloyeemodel',
            name='From_Date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='emplloyeemodel',
            name='Gender',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Name should be between 3 to 12 characters and contain only letters.', regex='^(?=.{3,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')]),
        ),
        migrations.AlterField(
            model_name='emplloyeemodel',
            name='H_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='emplloyeemodel',
            name='Name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Name should be between 3 to 12 characters and contain only letters.', regex='^(?=.{3,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')]),
        ),
        migrations.AlterField(
            model_name='emplloyeemodel',
            name='Phone_No',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='emplloyeemodel',
            name='Qualification_Name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='This field must contain only letters and numbers.', regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='emplloyeemodel',
            name='State',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='This field must contain only letters and numbers.', regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='emplloyeemodel',
            name='Street',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='This field must contain only letters and numbers.', regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='emplloyeemodel',
            name='Title',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='This field must contain only letters and numbers.', regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='emplloyeemodel',
            name='To_Date',
            field=models.CharField(max_length=30),
        ),
    ]
